version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASES=postgres,test
    ports:
      - "5435:5432"
    volumes:
      - ./scripts/pg-init:/docker-entrypoint-initdb.d
